### ISSUE TITLE
RHDP: Ansible Windows Workshop (Ad-hoc commands) section

### ISSUE THREAD

**Issue by rhjcd** [ansible/workshops#1991]
### Problem Summary

Link to thread: https://chat.google.com/room/AAAAIFjw_Tw/euRR2R_ub3Y

This is a credssp issue that seems to still exist
Go to inventory, workshop inventory, groups, windows
Change ansible_winrm_transport: credssp
To be ntlm
ansible_winrm_transport: ntlm

Section 1: Ad hoc commands, Step 1 fails with the following errors:

   SSH password: 
student1-win1 | UNREACHABLE! => {
    "changed": false,
    "msg": "credssp: argument of type 'NoneType' is not iterable",
    "unreachable": true
}
TypeError: Cannot read properties of undefined (reading 'host')

### Issue Type

Bug

### Extra vars file

NA

### Ansible Playbook Output

Ad hoc commands, Step 1 fails with the following errors:

   SSH password: 
student1-win1 | UNREACHABLE! => {
    "changed": false,
    "msg": "credssp: argument of type 'NoneType' is not iterable",
    "unreachable": true
}
TypeError: Cannot read properties of undefined (reading 'host')
    at xfe (https://student1.bpfg4.example.opentlc.com/static/js/main.2552dea1.js:2:3341400)
    at oo (https://student1.bpfg4.example.opentlc.com/static/js/main.2552dea1.js:2:850659)
    at Ks (https://student1.bpfg4.example.opentlc.com/static/js/main.2552dea1.js:2:902959)
    at Al (https://student1.bpfg4.example.opentlc.com/static/js/main.2552dea1.js:2:890200)
    at Tl (https://student1.bpfg4.example.opentlc.com/static/js/main.2552dea1.js:2:890128)
    at El (https://student1.bpfg4.example.opentlc.com/static/js/main.2552dea1.js:2:889991)
    at yl (https://student1.bpfg4.example.opentlc.com/static/js/main.2552dea1.js:2:886957)
    at https://student1.bpfg4.example.opentlc.com/static/js/main.2552dea1.js:2:836451
    at t.unstable_runWithPriority (https://student1.bpfg4.example.opentlc.com/static/js/main.2552dea1.js:2:932713)
    at Vi (https://student1.bpfg4.example.opentlc.com/static/js/main.2552dea1.js:2:83622

### Ansible Version

NA

### Ansible Configuration

NA

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

RHEL

**Comment by cbolz** [comment]
I ran into this as well. What worked for me is to just use the default EE instead of the workshop EE.

**Comment by cbolz** [comment]
> I ran into this as well. What worked for me is to just use the default EE instead of the workshop EE.

ignore this, fixing ansible_winrm_transport is the right way - my workaround fails later in the lab...

**Comment by IPvSean** [comment]
I think I fixed this, can you please re-open if this is still an issue?

**Comment by gglm92** [comment]
@IPvSean what did you do? I have the same error on my environment.

**Comment by IPvSean** [comment]
@gglm92 our inventory is set like this->

```
[windows:vars]
ansible_connection=winrm
ansible_winrm_transport=credssp
ansible_winrm_server_cert_validation=ignore
ansible_port=5986
```

I am pretty sure what happened was a bug with the execution environment (EE) which has been fixed.  Try using a supported EE, or just update your EE.  If you have more questions, try opening a thread on forum.ansible.com
