### ISSUE TITLE
Bug report for Ansible Workshops - Configuration as Code for Ansible Automation Platform 2

### ISSUE THREAD

**Issue by daleroux** [ansible/workshops#2078]
### Problem Summary

Step 2 of the workshop: Install our ee_utilities collection and containers.podman using ansible-galaxy command. Make sure the versions are correct. 

ansible-galaxy collection install infra.ee_utilities:3.1.2 containers.podman:1.10.3 community.general:7.3.0

The above command will error out pm the community.general  collection.

Downloading community.general:7.3.0 and installing it manually will work, though and it the workaround I used.

### Issue Type

Bug

### Extra vars file

N/A

### Ansible Playbook Output

$ ansible-galaxy collection install infra.ee_utilities:3.1.2 containers.podman:1.10.3 community.general:7.3.0  -vvv
ansible-galaxy [core 2.13.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/student/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/student/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-galaxy
  python version = 3.9.7 (default, Sep 13 2021, 08:18:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
Starting galaxy collection install process
Process install dependency map
Opened /home/student/.ansible/galaxy_token
[WARNING]: Skipping Galaxy server https://galaxy.ansible.com/api/. Got an unexpected error when getting
available versions of collection community.general:
'/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'
ERROR! Unexpected Exception, this is probably a bug: '/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'
the full traceback was:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'community.general'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ansible/cli/__init__.py", line 601, in cli_executor
    exit_code = cli.run()
  File "/usr/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 647, in run
    return context.CLIARGS['func']()
  File "/usr/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 102, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 1297, in execute_install
    self._execute_install_collection(
  File "/usr/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 1325, in _execute_install_collection
    install_collections(
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/collection/__init__.py", line 705, in install_collections
    dependency_map = _resolve_depenency_map(
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/collection/__init__.py", line 1637, in _resolve_depenency_map
    return collection_dep_resolver.resolve(
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 79, in from_requirement
    cands = build_iter_view(provider.find_matches([requirement]))
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/dependency_resolution/providers.py", line 494, in find_matches
    return self._find_matches(requirements)
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/dependency_resolution/providers.py", line 320, in _find_matches
    coll_versions = self._api_proxy.get_collection_versions(first_req)
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/collection/galaxy_api_proxy.py", line 95, in get_collection_versions
    return set(
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/collection/galaxy_api_proxy.py", line 95, in <genexpr>
    return set(
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/collection/galaxy_api_proxy.py", line 76, in _get_collection_versions
    raise last_error
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/collection/galaxy_api_proxy.py", line 55, in _get_collection_versions
    versions = api.get_collection_versions(requirement.namespace, requirement.name)
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/api.py", line 121, in wrapped
    return method(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/api.py", line 870, in get_collection_versions
    data = self._call_galaxy(to_native(next_link, errors='surrogate_or_strict'),
  File "/usr/lib/python3.9/site-packages/ansible/module_utils/api.py", line 164, in run_function
    return call_retryable_function()
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/api.py", line 395, in _call_galaxy
    path_cache = self._cache[cache_id][url_info.path]
KeyError: '/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'
[student@ansible-1 ~]$ ansible-galaxy collection install infra.ee_utilities:3.1.2 containers.podman:1.10.3  
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/infra-ee_utilities-3.1.2.tar.gz to /home/student/.ansible/tmp/ansible-local-180295_mictfo/tmpbion24vo/infra-ee_utilities-3.1.2-tz9z6ev8
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/containers-podman-1.10.3.tar.gz to /home/student/.ansible/tmp/ansible-local-180295_mictfo/tmpbion24vo/containers-podman-1.10.3-8ixs160e
Installing 'infra.ee_utilities:3.1.2' to '/home/student/.ansible/collections/ansible_collections/infra/ee_utilities'
infra.ee_utilities:3.1.2 was installed successfully
Installing 'containers.podman:1.10.3' to '/home/student/.ansible/collections/ansible_collections/containers/podman'
containers.podman:1.10.3 was installed successfully
[student@ansible-1 ~]$ ansible-galaxy collection install community.general:7.3.0
Starting galaxy collection install process
Process install dependency map
[WARNING]: Skipping Galaxy server https://galaxy.ansible.com/api/. Got an unexpected error when getting
available versions of collection community.general:
'/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'
ERROR! Unexpected Exception, this is probably a bug: '/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'
to see the full traceback, use -vvv

### Ansible Version

ansible [core 2.13.2]
  config file = /home/student/ansible.cfg
  configured module search path = ['/home/student/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/student/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Sep 13 2021, 08:18:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.3
  libyaml = True

### Ansible Configuration

DEFAULT_VAULT_PASSWORD_FILE(/home/student/ansible.cfg) = /home/student/.password

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

Red Hat Enterprise Linux release 8.6 (Ootpa)

**Comment by abenokraitis** [comment]
@sean-m-sullivan FYI

**Comment by daleroux** [comment]
closing the issue as it's fixed in the new lab at  https://play.instruqt.com/redhat/invite/yinrttmwemvw
