### ISSUE TITLE
workshop_type: f5 - f5_setup : Install AS3 task broken with ansible devel

### ISSUE THREAD

**Issue by Spredzy** [ansible/workshops#387]
##### SUMMARY

the `[f5_setup : Install AS3]` task is broken with ansible `devel`

##### ISSUE TYPE

 - Bug Report

##### PLAYBOOK LONG OUTPUT

```
TASK [f5_setup : Install AS3] **************************************************
[0;33mchanged: [tower-qe-networking-tower-devel-null-237-student2-ansible][0m
[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'HTTPError' object has no attribute 'headers'[0m
[0;31mfatal: [tower-qe-f5-tower-devel-null-237-student2-f5]: FAILED! => changed=false [0m
[0;31m  module_stderr: |-[0m
[0;31m    Traceback (most recent call last):[0m
[0;31m      File "/root/.ansible/tmp/ansible-tmp-1566181273.19-36023642980504/AnsiballZ__bigip_iapplx_package.py", line 125, in <module>[0m
[0;31m        _ansiballz_main()[0m
[0;31m      File "/root/.ansible/tmp/ansible-tmp-1566181273.19-36023642980504/AnsiballZ__bigip_iapplx_package.py", line 117, in _ansiballz_main[0m
[0;31m        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)[0m
[0;31m      File "/root/.ansible/tmp/ansible-tmp-1566181273.19-36023642980504/AnsiballZ__bigip_iapplx_package.py", line 54, in invoke_module[0m
[0;31m        imp.load_module('__main__', mod, module, MOD_DESC)[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_booA5x/__main__.py", line 480, in <module>[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_booA5x/__main__.py", line 473, in main[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_booA5x/__main__.py", line 202, in exec_module[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_booA5x/ansible_bigip_iapplx_package_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 529, in tmos_version[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_booA5x/ansible_bigip_iapplx_package_payload.zip/ansible/module_utils/network/f5/bigip.py", line 34, in api[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_booA5x/ansible_bigip_iapplx_package_payload.zip/ansible/module_utils/network/f5/bigip.py", line 77, in connect_via_basic_auth[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_booA5x/ansible_bigip_iapplx_package_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 232, in get[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_booA5x/ansible_bigip_iapplx_package_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 222, in send[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_booA5x/ansible_bigip_iapplx_package_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 163, in update_response[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_booA5x/ansible_bigip_iapplx_package_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 160, in get_headers[0m
[0;31m    AttributeError: 'HTTPError' object has no attribute 'headers'[0m
[0;31m  module_stdout: ''[0m
[0;31m  msg: |-[0m
[0;31m    MODULE FAILURE[0m
[0;31m    See stdout/stderr for the exact error[0m
[0;31m  rc: 1[0m
[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'HTTPError' object has no attribute 'headers'[0m
[0;31mfatal: [tower-qe-f5-tower-devel-null-237-student1-f5]: FAILED! => changed=false [0m
[0;31m  module_stderr: |-[0m
[0;31m    Traceback (most recent call last):[0m
[0;31m      File "/root/.ansible/tmp/ansible-tmp-1566181273.2-112878905654684/AnsiballZ__bigip_iapplx_package.py", line 125, in <module>[0m
[0;31m        _ansiballz_main()[0m
[0;31m      File "/root/.ansible/tmp/ansible-tmp-1566181273.2-112878905654684/AnsiballZ__bigip_iapplx_package.py", line 117, in _ansiballz_main[0m
[0;31m        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)[0m
[0;31m      File "/root/.ansible/tmp/ansible-tmp-1566181273.2-112878905654684/AnsiballZ__bigip_iapplx_package.py", line 54, in invoke_module[0m
[0;31m        imp.load_module('__main__', mod, module, MOD_DESC)[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_wW9Znr/__main__.py", line 480, in <module>[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_wW9Znr/__main__.py", line 473, in main[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_wW9Znr/__main__.py", line 202, in exec_module[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_wW9Znr/ansible_bigip_iapplx_package_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 529, in tmos_version[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_wW9Znr/ansible_bigip_iapplx_package_payload.zip/ansible/module_utils/network/f5/bigip.py", line 34, in api[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_wW9Znr/ansible_bigip_iapplx_package_payload.zip/ansible/module_utils/network/f5/bigip.py", line 77, in connect_via_basic_auth[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_wW9Znr/ansible_bigip_iapplx_package_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 232, in get[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_wW9Znr/ansible_bigip_iapplx_package_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 222, in send[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_wW9Znr/ansible_bigip_iapplx_package_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 163, in update_response[0m
[0;31m      File "/tmp/ansible_bigip_iapplx_package_payload_wW9Znr/ansible_bigip_iapplx_package_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 160, in get_headers[0m
[0;31m    AttributeError: 'HTTPError' object has no attribute 'headers'[0m
[0;31m  module_stdout: ''[0m
[0;31m  msg: |-[0m
[0;31m    MODULE FAILURE[0m
[0;31m    See stdout/stderr for the exact error[0m
[0;31m  rc: 1[0m
```

**Comment by IPvSean** [comment]
tagging @ericzji

**Comment by IPvSean** [comment]
Hey Eric to recreate this you need to just provision a f5 workbench and then install ansible development and then you need to test the as3 exercise

```
$ pip install --user git+https://github.com/ansible/ansible.git@devel
```

**Comment by focrensh** [comment]
I ran the tasks at https://github.com/ansible/workshops/blob/master/provisioner/roles/f5_setup/tasks/main.yml against a lab box using 2.9dev ansible and it worked without issue.

It could be that the new BIG-IP is not fully online yet. The current tasks only check to make sure port 8443 is responding, but the API may not be fully up yet.

I will add the bigip_wait module back into the flow after the admin password is set, this should verify AS3 is ready to be installed via REST.

Will send PR once done.

**Comment by focrensh** [comment]
@IPvSean are you able to confirm in the pipeline logs if this error is gone now?

**Comment by IPvSean** [comment]
@focrensh this i only an issue on 2.9.0 stable, not on devel.  We have pinned the workshops to ansible 2.9.1 and newer for now to resolve this issue so I think I can close this.
