### ISSUE TITLE
Ansible Workshop deploying Windows fails due to gitlab role breaking -

### ISSUE THREAD

**Issue by tonykay** [ansible/workshops#717]
##### SUMMARY

Deploying the windows workshop (from head of master) gitlab failure breaks the deploy. This is a known issue related to el 7 and documented in a similar situation in skylight. See here; 

https://github.com/mgmt-sa-tiger-team/skylight/issues/93#issuecomment-591337665

##### ISSUE TYPE

 - Bug Report

##### EXTRA VARS FILE

```
$ cat ~windows_workshop.yml
---
instance_loc: ec2
ec2_region: us-east-1
ec2_name_prefix: tokwin00

workshop_dns_zone:      rhdemo.io

student_total: 2
workshop_type: windows
doubleup: false
admin_password: ansible123
create_login_page: true
towerinstall: false
autolicense: false
```

##### ANSIBLE VERSION

```
provisioner]$ ansible --version
ansible 2.9.4
  config file = /tmp/workshops/provisioner/ansible.cfg
  configured module search path = [u'/home/opentlc-mgr/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/opentlc-mgr/virtualenvs/linklight-ansible-2.9/lib/python2.7/site-packages/ansible
  executable location = /home/opentlc-mgr/virtualenvs/linklight-ansible-2.9/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```
ansible-config dump --only-changed
DEFAULT_CALLBACK_WHITELIST(/tmp/workshops/provisioner/ansible.cfg) = [u'time']
DEFAULT_FORKS(/tmp/workshops/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/tmp/workshops/provisioner/ansible.cfg) = [u'/tmp/workshops/provisioner/hosts']
DEFAULT_NO_TARGET_SYSLOG(/tmp/workshops/provisioner/ansible.cfg) = False
DEFAULT_SCP_IF_SSH(/tmp/workshops/provisioner/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/tmp/workshops/provisioner/ansible.cfg) = yaml
HOST_KEY_CHECKING(/tmp/workshops/provisioner/ansible.cfg) = False
INTERPRETER_PYTHON(/tmp/workshops/provisioner/ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/tmp/workshops/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/tmp/workshops/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/tmp/workshops/provisioner/ansible.cfg) = False
```

##### OS / ENVIRONMENT
RHEL 7.4
```
uname -a
Linux admin-dev.na.shared.opentlc.com 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Dec 28 14:23:39 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
(linklight-ansible-2.9) [opentlc-mgr@admin-dev (DEV) provisioner]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)
(linklight-ansible-2.9) [opentlc-mgr@admin-dev (DEV) provisioner]$```

##### TOWER

Engine

##### PLAYBOOK SHORT OUTPUT


```paste below
TASK [gitlab-server : GitLab Post | Execute set root password] ***************************************************************************************
fatal: [gitlab]: FAILED! => changed=true
  cmd:
  - ./set_root_pw.sh
  delta: '0:00:01.477138'
  end: '2020-02-28 23:45:23.965795'
  msg: non-zero return code
  rc: 1
  start: '2020-02-28 23:45:22.488657'
  stderr: |-
    /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:506:in `handle_argument_error': ERROR: "rails console" was called with arguments ["production"] (Thor::InvocationError)
    Usage: "rails console [options]"
```

##### PLAYBOOK LONG OUTPUT

```
TASK [gitlab-server : GitLab Post | Copy root password script to host] *******************************************************************************
changed: [gitlab]

TASK [gitlab-server : GitLab Post | Execute set root password] ***************************************************************************************
fatal: [gitlab]: FAILED! => changed=true
  cmd:
  - ./set_root_pw.sh
  delta: '0:00:01.477138'
  end: '2020-02-28 23:45:23.965795'
  msg: non-zero return code
  rc: 1
  start: '2020-02-28 23:45:22.488657'
  stderr: |-
    /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:506:in `handle_argument_error': ERROR: "rails console" was called with arguments ["production"] (Thor::InvocationError)
    Usage: "rails console [options]"
            from /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:34:in `rescue in run'
            from /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:20:in `run'
            from /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
            from /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
            from /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/command/base.rb:69:in `perform'
            from /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/command.rb:46:in `invoke'
            from /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/commands.rb:18:in `<top (required)>'
            from bin/rails:4:in `require'
            from bin/rails:4:in `<main>'
    /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/commands/console/console_command.rb:95:in `perform': wrong number of arguments (given 1, expected 0) (ArgumentError)
            from /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
            from /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
            from /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
            from /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/command/base.rb:69:in `perform'
            from /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/command.rb:46:in `invoke'
            from /opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/railties-6.0.2/lib/rails/commands.rb:18:in `<top (required)>'
            from bin/rails:4:in `require'
            from bin/rails:4:in `<main>'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

RUNNING HANDLER [geerlingguy.gitlab : restart gitlab] ************************************************************************************************

PLAY RECAP *******************************************************************************************************************************************
gitlab                     : ok=32   changed=21   unreachable=0    failed=1    skipped=6    rescued=1    ignored=1
localhost                  : ok=60   changed=26   unreachable=0    failed=0    skipped=27   rescued=0    ignored=0
tokwin00-student1-ansible  : ok=30   changed=22   unreachable=0    failed=0    skipped=16   rescued=0    ignored=1
tokwin00-student2-ansible  : ok=30   changed=22   unreachable=0    failed=0    skipped=18   rescued=0    ignored=1
```

**Comment by cloin** [comment]
Fixed on devel here: https://github.com/ansible/workshops/pull/706/files

**Comment by liquidat** [comment]
@cloin @tonykay Can we close this?

**Comment by IPvSean** [comment]
this is now merged, please re-open if this is still an issue https://github.com/ansible/workshops/pull/800
